server:
  port: 6000
spring:
  application:
    name: account-query
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3306/bankAccount
      username: root
      password: Andres20
    kafka:
      listener:
        ack-mode: MANUAL_IMMEDIATE
      consumer:
        bootstrap-servers: localhost:9092
        group-id: account-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        auto-offset-reset: earliest
        properties:
          spring:
            json:
              trusted:
                packages: "*"
